FROM rust:latest AS builder

RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf var/lin/apt/lists/*
WORKDIR /build 

COPY server/ .
ENV SQLX_OFFLINE=true

RUN cargo build --release 
FROM debian:bookworm-slim 

RUN apt-get update && apt-get install -y ca-certificates libssl3 libpq5 && rm -rf var/lin/apt/lists/*
WORKDIR /app

COPY --from=builder /build/target/release/server ./server 
EXPOSE 8000

CMD ["./server"]

