name: Rust CI

on: 
  push:
    branches: [ "feats/**", "feat/**" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server_rust

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          server_rust -> target

    - name: Check formatting
      working-directory: ./server_rust
      run: cargo fmt -- --check
    
    - name: Test
      working-directory: ./server_rust
      run: cargo test --all-features
